/*!
# cuda-energy

ATP/energy system for autonomous agent fleets.

Every agent has an energy budget (ATP) that is:
- Generated by the Rest instinct (time-based)
- Consumed by all other operations (perception cheap, deliberation expensive)
- Subject to fleet-level distribution and priority allocation
- Monitored for apoptosis (self-termination when energy depletes)

Inspired by biological mitochondria — the cell's power plant.
*/

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Energy budget for a single agent
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EnergyBudget {
    pub current_atp: f64,
    pub max_atp: f64,
    pub generation_rate: f64,    // ATP per tick (from Rest instinct)
    pub debt_limit: f64,          // max negative before apoptosis
    pub total_generated: f64,
    pub total_consumed: f64,
}

impl EnergyBudget {
    pub fn new(max: f64, gen_rate: f64) -> Self {
        EnergyBudget { current_atp: max, max_atp: max, generation_rate: gen_rate, debt_limit: -max * 0.5, total_generated: 0.0, total_consumed: 0.0 }
    }

    pub fn generate(&mut self) -> f64 {
        let gen = self.generation_rate.min(self.max_atp - self.current_atp);
        self.current_atp += gen;
        self.total_generated += gen;
        gen
    }

    pub fn consume(&mut self, amount: f64) -> bool {
        if self.current_atp - amount < self.debt_limit { return false; }
        self.current_atp -= amount;
        self.total_consumed += amount;
        true
    }

    pub fn ratio(&self) -> f64 { self.current_atp / self.max_atp }

    pub fn is_depleted(&self) -> bool { self.current_atp <= self.debt_limit }
}

/// Energy cost per operation type
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EnergyCosts {
    pub perception: f64,      // IO_READ, SENSOR_ACQUIRE
    pub arithmetic: f64,      // CADD, CSUB, etc.
    pub deliberation: f64,    // CONSIDER, RESOLVE
    pub communication: f64,   // TELL, ASK, DELEGATE
    pub memory: f64,          // LOAD, STORE, REGION ops
    pub instinct: f64,        // INSTINCT_ACTIVATE, GENE_EXPR
    pub apoptosis: f64,       // APOPTOSIS_TRIGGER (free)
    pub rest: f64,            // REST instinct (generates, not consumes)
}

impl Default for EnergyCosts {
    fn default() -> Self {
        EnergyCosts { perception: 0.5, arithmetic: 0.1, deliberation: 2.0, communication: 1.0, memory: 0.2, instinct: 0.8, apoptosis: 0.0, rest: -1.0 }
    }
}

/// Circadian rhythm — modulates instinct strength based on time
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CircadianRhythm {
    /// Hour of peak Navigate strength (0-23)
    pub navigate_peak: f64,
    /// Hour of peak Rest strength
    pub rest_peak: f64,
    /// Period in hours (24.0 for daily)
    pub period: f64,
    /// Minimum modulation (never fully suppresses)
    pub floor: f64,
}

impl CircadianRhythm {
    pub fn new() -> Self {
        CircadianRhythm { navigate_peak: 12.0, rest_peak: 2.0, period: 24.0, floor: 0.1 }
    }

    /// Get modulation factor for an instinct at a given hour
    /// Returns 0.0-1.0 where 1.0 = peak strength
    pub fn modulation(&self, instinct_peak_hour: f64, current_hour: f64) -> f64 {
        let phase = ((current_hour - instinct_peak_hour) / self.period) * 2.0 * std::f64::consts::PI;
        let raw = (phase.cos() + 1.0) / 2.0; // 0-1
        self.floor + raw * (1.0 - self.floor)
    }

    /// Navigate instinct strength at given hour
    pub fn navigate_strength(&self, hour: f64) -> f64 { self.modulation(self.navigate_peak, hour) }

    /// Rest instinct strength at given hour
    pub fn rest_strength(&self, hour: f64) -> f64 { self.modulation(self.rest_peak, hour) }
}

/// Epigenetic memory — experience modifies instinct weights over time
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EpigeneticMemory {
    /// instinct_name -> accumulated reinforcement (positive=strengthen, negative=weaken)
    pub modifications: HashMap<String, f64>,
    /// Learning rate (how fast experiences modify weights)
    pub learning_rate: f64,
    /// Decay rate (natural forgetting)
    pub decay_rate: f64,
}

impl EpigeneticMemory {
    pub fn new() -> Self {
        EpigeneticMemory { modifications: HashMap::new(), learning_rate: 0.1, decay_rate: 0.01 }
    }

    /// Reinforce an instinct based on outcome
    /// outcome: positive = good outcome (strengthen), negative = bad outcome (weaken)
    pub fn reinforce(&mut self, instinct: &str, outcome: f64) {
        let current = self.modifications.get(instinct).copied().unwrap_or(0.0);
        let delta = outcome * self.learning_rate;
        let new_val = (current + delta).clamp(-1.0, 1.0);
        self.modifications.insert(instinct.to_string(), new_val);
    }

    /// Get the weight modifier for an instinct
    pub fn weight(&self, instinct: &str) -> f64 {
        self.modifications.get(instinct).copied().unwrap_or(0.0)
    }

    /// Apply time-based decay (call periodically)
    pub fn decay(&mut self) {
        for val in self.modifications.values_mut() { *val *= 1.0 - self.decay_rate; }
    }
}

/// Apoptosis protocol — graceful agent self-termination
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ApoptosisProtocol {
    /// Energy ratio below which apoptosis is considered (0.0-1.0)
    pub energy_threshold: f64,
    /// Fitness below which apoptosis triggers (0.0-1.0)
    pub fitness_threshold: f64,
    /// Number of consecutive low-fitness ticks before triggering
    pub patience_ticks: u32,
    /// Current consecutive low ticks
    pub low_ticks: u32,
    /// Whether apoptosis has been triggered
    pub triggered: bool,
    /// Reason for apoptosis
    pub reason: String,
}

impl ApoptosisProtocol {
    pub fn new() -> Self {
        ApoptosisProtocol { energy_threshold: 0.05, fitness_threshold: 0.1, patience_ticks: 10, low_ticks: 0, triggered: false, reason: String::new() }
    }

    /// Check if apoptosis should trigger. Returns true if agent should terminate.
    pub fn check(&mut self, energy_ratio: f64, fitness: f64) -> bool {
        if self.triggered { return true; }
        let energy_low = energy_ratio < self.energy_threshold;
        let fitness_low = fitness < self.fitness_threshold;
        if energy_low || fitness_low {
            self.low_ticks += 1;
            if self.low_ticks >= self.patience_ticks {
                self.triggered = true;
                self.reason = if energy_low { format!("Energy depleted: {:.1}%", energy_ratio * 100.0) }
                           else { format!("Fitness too low: {:.3}", fitness) };
                return true;
            }
        } else {
            self.low_ticks = self.low_ticks.saturating_sub(1);
        }
        false
    }

    /// Graceful shutdown: returns a summary of the agent's life
    pub fn shutdown_summary(&self, budget: &EnergyBudget) -> String {
        format!("Apoptosis: {}. ATP: {:.1}/{:.1} ({:.0}% generated, {:.0}% consumed)",
            self.reason, budget.current_atp, budget.max_atp,
            if budget.max_atp > 0.0 { budget.total_generated / budget.max_atp * 100.0 } else { 0.0 },
            if budget.total_consumed > 0.0 { budget.total_consumed / budget.max_atp * 100.0 } else { 0.0 })
    }
}

/// Fleet-level energy distribution
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FleetEnergy {
    pub agents: HashMap<String, EnergyBudget>,
    pub shared_pool: f64,
    pub shared_generation_rate: f64,
    pub costs: EnergyCosts,
    pub circadian: CircadianRhythm,
}

impl FleetEnergy {
    pub fn new() -> Self {
        FleetEnergy { agents: HashMap::new(), shared_pool: 0.0, shared_generation_rate: 0.0, costs: EnergyCosts::default(), circadian: CircadianRhythm::new() }
    }

    pub fn add_agent(&mut self, id: &str, max_atp: f64, gen_rate: f64) {
        self.agents.insert(id.to_string(), EnergyBudget::new(max_atp, gen_rate));
    }

    pub fn tick(&mut self, hour: f64) {
        // Generate energy for each agent (modulated by circadian rhythm)
        for (_id, budget) in &mut self.agents {
            let rest_mod = self.circadian.rest_strength(hour);
            budget.generation_rate = budget.generation_rate.max(0.0) * (0.5 + rest_mod * 0.5);
            budget.generate();
        }
        // Generate shared pool
        self.shared_pool += self.shared_generation_rate;
    }

    /// Transfer energy from shared pool to agent
    pub fn distribute(&mut self, agent_id: &str, amount: f64) -> bool {
        if self.shared_pool < amount { return false; }
        if let Some(budget) = self.agents.get_mut(agent_id) {
            self.shared_pool -= amount;
            budget.current_atp = (budget.current_atp + amount).min(budget.max_atp);
            return true;
        }
        false
    }

    /// Agent requests energy from fleet pool
    pub fn request_energy(&mut self, agent_id: &str, amount: f64) -> f64 {
        let granted = amount.min(self.shared_pool);
        if granted > 0.0 { self.distribute(agent_id, granted); }
        granted
    }

    /// Get total fleet ATP
    pub fn total_atp(&self) -> f64 {
        self.agents.values().map(|b| b.current_atp).sum::<f64>() + self.shared_pool
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_energy_budget_basic() {
        let mut b = EnergyBudget::new(100.0, 5.0);
        assert_eq!(b.current_atp, 100.0);
        let gen = b.generate();
        assert!(gen <= 0.0); // already full
        assert!(b.consume(50.0));
        assert_eq!(b.current_atp, 50.0);
        let gen = b.generate();
        assert_eq!(gen, 5.0);
        assert_eq!(b.current_atp, 55.0);
    }

    #[test]
    fn test_energy_budget_debt() {
        let mut b = EnergyBudget::new(100.0, 0.0);
        b.current_atp = -45.0; // approaching debt_limit=-50
        assert!(!b.consume(10.0)); // -45 - 10 = -55 < -50, blocked by debt limit
        assert_eq!(b.current_atp, -45.0); // no change since consume was rejected
    }

    #[test]
    fn test_apoptosis_triggered() {
        let mut apo = ApoptosisProtocol::new();
        apo.patience_ticks = 3;
        assert!(!apo.check(0.03, 0.5)); // low energy, tick 1
        assert!(!apo.check(0.03, 0.5)); // tick 2
        assert!(apo.check(0.03, 0.5)); // tick 3 -> triggered
        assert!(apo.triggered);
        assert!(!apo.reason.is_empty());
    }

    #[test]
    fn test_apoptosis_recovery() {
        let mut apo = ApoptosisProtocol::new();
        apo.patience_ticks = 5;
        apo.check(0.03, 0.5); apo.check(0.03, 0.5); // 2 low ticks
        apo.check(0.5, 0.8); // recovery -> ticks decrease
        assert_eq!(apo.low_ticks, 1);
    }

    #[test]
    fn test_circadian_modulation() {
        let c = CircadianRhythm::new();
        // At navigate peak (12:00), navigate strength should be high
        let nav_noon = c.navigate_strength(12.0);
        let nav_midnight = c.navigate_strength(0.0);
        assert!(nav_noon > nav_midnight);
        // Rest should be strong at rest_peak (2:00)
        let rest_2am = c.rest_strength(2.0);
        let rest_noon = c.rest_strength(12.0);
        assert!(rest_2am > rest_noon);
    }

    #[test]
    fn test_epigenetic_memory() {
        let mut mem = EpigeneticMemory::new();
        mem.reinforce("navigate", 1.0); // good outcome
        mem.reinforce("navigate", 1.0); // another good
        assert!(mem.weight("navigate") > 0.0);
        mem.reinforce("navigate", -1.0); // bad outcome
        // Should still be positive (two +1s, one -1, with learning_rate=0.1)
        assert!(mem.weight("navigate") > 0.0);
        assert_eq!(mem.weight("unknown"), 0.0);
    }

    #[test]
    fn test_epigenetic_decay() {
        let mut mem = EpigeneticMemory::new();
        mem.reinforce("perceive", 1.0);
        let w1 = mem.weight("perceive");
        mem.decay();
        let w2 = mem.weight("perceive");
        assert!(w2 < w1);
    }

    #[test]
    fn test_fleet_energy() {
        let mut fleet = FleetEnergy::new();
        fleet.add_agent("agent-1", 100.0, 2.0);
        fleet.add_agent("agent-2", 50.0, 1.0);
        fleet.shared_pool = 50.0;
        assert!(fleet.distribute("agent-1", 30.0));
        assert!(!fleet.distribute("agent-2", 30.0)); // only 20 left
        assert!(fleet.distribute("agent-2", 20.0));
    }

    #[test]
    fn test_shutdown_summary() {
        let mut apo = ApoptosisProtocol::new();
        apo.patience_ticks = 1;
        let mut b = EnergyBudget::new(100.0, 5.0);
        b.consume(95.0);
        apo.check(b.ratio(), 0.05);
        let summary = apo.shutdown_summary(&b);
        assert!(summary.contains("Apoptosis"));
    }

    #[test]
    fn test_energy_costs_default() {
        let costs = EnergyCosts::default();
        assert!(costs.deliberation > costs.arithmetic);
        assert!(costs.communication > costs.perception);
        assert_eq!(costs.apoptosis, 0.0);
    }

    #[test]
    fn test_circadian_floor() {
        let c = CircadianRhythm::new();
        // Even at worst time, modulation should be >= floor
        for h in 0..24 {
            let m = c.navigate_strength(h as f64);
            assert!(m >= c.floor);
        }
    }

    #[test]
    fn test_fleet_total_atp() {
        let mut fleet = FleetEnergy::new();
        fleet.add_agent("a", 100.0, 0.0);
        fleet.shared_pool = 25.0;
        assert_eq!(fleet.total_atp(), 125.0);
    }
}
